export const Corps = {
    'DE':
    {
        'Objet - Type de décision': [],
        'Objet - Action': [],
        'Objet - Finalité': [],
        'Objet - Destinataire': [],
        'Objet - Contexte': [],
    },
    'AR':
    {
        'Objet - Action': [],
        'Objet - Domaine': [],
        'Objet - Contexte': [],
    },
    'AI':
    {
        'Objet - Action': [],
        'Objet - Destinataire': [],
        'Objet - Domaine': [],
        'Objet - Contexte': [],
        'Nom de la personne': [],
        'Cadre d\'emploi': [],
        'Echelon': [],
        'Fonctions': [],
        'IBM': [],
        'Nom de la personne': [],
        'Cadre d\'emploi': [],
        'Echelon': [],
        'Fonctions': [],
        'Durée de recrutement': [],
        'Fondement juridique': [],
        'Motif du recrutement': [
            'Accroisement temporaire d\'activité',
            'Accroissement saisonnnier d\'activité',
            'Projet ou opération',
            'Remplacement temporaire d\'un agent',
            'Attente de recrutement d\'un titulaire',
            'Pas de cadre d\'emploi adapté',
            'Besoins du service/nature des fonctions',
            'Commune de moins de 1 000 habitants',
            'Commune nouvelle ',
            'Emploi à temps non complet',
        ],
        'Recherche de titulaire': [],
        'Indice brut majoré': [],
    },
    'CC':
    {
        'Objet - Type d\'engagement': [],
        'Objet - Action demandée': [],
        'Objet - Finalité de l\'obligation': [],
        'Objet - Contractant': [],
        'Objet - Contexte': [],
        'Nom de la personne': [],
        'Cadre d\'emploi': [],
        'Echelon': [],
        'Fonctions': [],
        'IBM': [],
        'Nom de la personne': [],
        'Cadre d\'emploi': [],
        'Echelon': [],
        'Fonctions': [],
        'Durée de recrutement': [],
        'Fondement': [],
        'Motif du recrutement': [
            'Accroisement temporaire d\'activité',
            'Accroissement saisonnnier d\'activité',
            'Projet ou opération',
            'Remplacement temporaire d\'un agent',
            'Attente de recrutement d\'un titulaire',
            'Pas de cadre d\'emploi adapté',
            'Besoins du service/nature des fonctions',
            'Commune de moins de 1 000 habitants',
            'Commune nouvelle ',
            'Emploi à temps non complet',
        ],
        'Recherche de titulaire': [],
        'Indice brut majoré': [],
        'Procédure': [
            'Sans publicité préalable',
            'Procédure adaptée',
            'Appel d\'offre ouvert',
            'Appel d\'offre restreint',
            'Procédure négociée',
            'Dialogue compétitif',
        ],
        'Technique d\'achat (facultatif)': [
            'Concours',
            'Système d\'acquisition dynamique',
            'Enchères électroniques',
        ],
        'Montant HT': [],
        'Attributaire': [],
        'Recours à commission d\'appel d\'offre': [],
        'Attributaire': [],
        'Montant total HT': [],
        'Durée totale': [],
        'Prestation': [],
        'Recours à une commision de délégation de service public': [],
    },
};
