export const PJ = {
    'DE':
    {
        'Accusé de réception': [],
        'Autre document': [],
        'Avenant au contrat de recrutement d\'agent': [],
        'Courrier de demande (demande de pièce, lettre d\'observation..)': [],
        'Courrier de réponse (demande de pièce, lettre d\'observation..)': [],
        'Courrier d\'observations': [],
        'Débat d\'orientation du plan d\'aménagement et de développement durable': [],
        'Décision arrêtant le projet': [],
        'Déclaration d\'intention d\'aliéner': [],
        'Déféré': [],
        'Délibération': [],
        'Demande d\'expertise': [],
        'Document d\'orientation et d\'objectif': [],
        'Documents pré-contractuels': [],
        'Dossier de l\'acte': [],
        'Enquête publique': [],
        'Fiche de suivi d\'instruction': [],
        'Fiche navette': [],
        'Fichier de signature électronique': [],
        'Note d\'observations': [],
        'Pièce complémentaire': [],
        'Plan de financement relatif à une demande de fonds de concours ou de financement': [],
        'Projet d\'aménagement et de développement durable': [],
        'Projet de contrat avec l\'organisme retenu': [],
        'Rapport biennal des avancements d\'échelons': [],
        'Rapport de présentation': [],
        'Réponse à une demande d\'expertise': [],
    },
    'AR':
    {
        'Accusé de réception': [],
        'Acte réglementaire': [],
        'Autre document': [],
        'Courrier de demande (demande de pièce, lettre d\'observation..)': [],
        'Courrier de réponse (demande de pièce, lettre d\'observation..)': [],
        'Courrier d\'observations': [],
        'Débat d\'orientation du plan d\'aménagement et de développement durable': [],
        'Décision arrêtant le projet': [],
        'Déféré': [],
        'Délibération de prescription': [],
        'Demande d\'expertise': [],
        'Document d\'orientation et d\'objectif': [],
        'Dossier de l\'acte': [],
        'Enquête publique': [],
        'Fiche de suivi d\'instruction': [],
        'Fiche navette': [],
        'Fichier de signature électronique': [],
        'Note d\'observations': [],
        'Pièce complémentaire': [],
        'Projet d\'aménagement et de développement durable': [],
        'Rapport de présentation': [],
        'Réponse à une demande d\'expertise': [],
    },
    'AI':
    {
        'Accord d\'une autorité administrative': [],
        'Accusé de réception': [],
        'Accusé de réception': [],
        'Acte individuel': [],
        'Agrément ou certificat': [],
        'Attestation fournie par l\'agent public': [],
        'Attestation fournie par le porteur de projet': [],
        'Autre document': [],
        'Avenant au contrat de recrutement d\'agent': [],
        'Avis': [],
        'Avis de création, de vacance ou de suppression de poste': [],
        'Avis de la commission administrative paritaire': [],
        'Avis de la commission mixte paritaire': [],
        'Avis de vacance d\'emploi': [],
        'Candidature sur le poste vacant': [],
        'Convention': [],
        'Courrier de demande (demande de pièce, lettre d\'observation..)': [],
        'Courrier de réponse (demande de pièce, lettre d\'observation..)': [],
        'Courrier d\'observations': [],
        'Décision': [],
        'Déféré': [],
        'Délibération établissant la liste de postes à pourvoir': [],
        'Demande': [],
        'Demande de l\'agent': [],
        'Demande d\'expertise': [],
        'Document photographique': [],
        'Dossier de l\'acte': [],
        'Fiche de suivi d\'instruction': [],
        'Fiche navette': [],
        'Fichier de signature électronique': [],
        'Information du centre de gestion': [],
        'Inscription sur la liste d\'aptitude': [],
        'Lettre': [],
        'Liste de postes à pourvoir': [],
        'Note d\'observations': [],
        'Notice explicative': [],
        'Pièce complémentaire': [],
        'Pièce du dossier de permis': [],
        'Plans': [],
        'Présentation des états initiaux et futurs': [],
        'Rapport d\'étude': [],
        'Réponse à une demande d\'expertise': [],
        'Tableau': [],
    },
    'CC':
    {
        'Accusé de réception': [],
        'Acte d\'engagement': [],
        'Attestation fournie par l\'agent public': [],
        'Autorisation d\'occupation du domaine public': [],
        'Autre document': [],
        'Avenant au contrat de recrutement d\'agent': [],
        'Avis d\'appel public à concurrence': [],
        'Avis de délégation': [],
        'Avis de la commission consultative des services publics locaux': [],
        'Avis de l\'autorité compétente de l\'Etat': [],
        'Avis de vacance d\'emploi': [],
        'Avis du jury de concours': [],
        'Bordereau des prix': [],
        'Cahier des charges de la délégation': [],
        'Cahier des clauses administratives particulières': [],
        'Cahier des clauses techniques particulières': [],
        'Candidature sur le poste vacant': [],
        'Contrat de délégation': [],
        'Contrat de vente': [],
        'Copie du jugement d\'homologation de la transaction': [],
        'Courrier de demande (demande de pièce, lettre d\'observation..)': [],
        'Courrier de réponse (demande de pièce, lettre d\'observation..)': [],
        'Courrier d\'observations': [],
        'Courriers de rejet des candidatures incomplètes ou irrecevables': [],
        'Déféré': [],
        'Délibération autorisant à passer le contrat': [],
        'Délibération autorisant l\'acquisition': [],
        'Délibération autorisant le recours aux contractuels': [],
        'Délibération constatant la désaffectation': [],
        'Délibération de déclassement': [],
        'Demande de cautionnement': [],
        'Demande d\'expertise': [],
        'Document contractuel': [],
        'Documents pré-contractuels': [],
        'Dossier de l\'acte': [],
        'Fiche de suivi d\'instruction': [],
        'Fiche navette': [],
        'Fichier de signature électronique': [],
        'Garantie d\'emprunt': [],
        'Invitation à présenter une offre': [],
        'Invitation des candidats à soumissionner': [],
        'Mémoire technique': [],
        'Modification du contrat': [],
        'Note d\'observations': [],
        'Notification du rejet des offres': [],
        'Pièce complémentaire': [],
        'Procès verbal de la commission d\'appel d\'offre ou du jury': [],
        'Procès verbal de la commission de délégation de service public': [],
        'Rapport de la commission d\'appel d\'offre': [],
        'Rapport de la commission de délégation du service public': [],
        'Rapport de présentation de l\'acheteur': [],
        'Rapport justifiant le choix du marché, les modalités et la procédure de passation': [],
        'Registre des dépôts des offres': [],
        'Règlement de concours': [],
        'Règlement de la consultation': [],
        'Renseignements, attestations et déclarations fournies par l\'attributaire': [],
        'Réponse à une demande d\'expertise': [],
    },
};
