/**
 * @constant
 * @desc every action type
 * @version 1.0
 * @since 1.0
 * @public
 */
export default {
    VALIDATION: 'VALIDATION::VALIDATION',
    VALIDATION_PENDING: 'VALIDATION::VALIDATION_PENDING',
    VALIDATION_FULFILLED: 'VALIDATION::VALIDATION_FULFILLED',
    VALIDATION_REJECTED: 'VALIDATION::VALIDATION_REJECTED',

    ACTE: 'VALIDATION::ACTE',
    ACTE_PENDING: 'VALIDATION::ACTE_PENDING',
    ACTE_REJECTED: 'VALIDATION::ACTE_REJECTED',
    ACTE_FULFILLED: 'VALIDATION::ACTE_FULFILLED',

    CLEAR_ERROR: 'VALIDATION:CLEAR_ERROR',
};
